
#CC = m68k-apple-macos-gcc
#CXX = m68k-apple-macos-gcc
CC = powerpc-apple-macos-gcc
CXX = powerpc-apple-macos-gcc


#CFLAGS=-I../../include -I.. -I/opt/local/include/SDL2 -I../../../stb
CFLAGS=-I../../include -I.. -I../../stb -I$(HOME)/Retro68-build/toolchain/powerpc-apple-macos/include/SDL2 -DSTBI_NO_THREAD_LOCALS

#LDFLAGS=-L../../lib -lTinyGL -L/opt/local/lib -lSDL2
LDFLAGS= -lm  


all:	gears

gears:	gears.o
	$(CC)  -o gears gears.o ../../src/*.o $(LDFLAGS)
#$(HOME)/sdl2macos9/bin2app.sh gears
	$(HOME)/sdl2macos9/xcoff2app.sh gears
	
clean:
	rm -rf game hello gears model texture *.o *.APPL *.bin *.gdb *.dsk *.pef

