
CC = m68k-apple-macos-gcc
CXX = m68k-apple-macos-gcc


CFLAGS=-I../../include -I.. -I../../stb -I$(HOME)/Retro68-build/toolchain/m68k-apple-macos/include/SDL2 -DSTBI_NO_THREAD_LOCALS
LDFLAGS= -lm  
#CFLAGS=-I../../include -I.. -I/opt/local/include/SDL2 -I../../../stb
#LDFLAGS=-L../../lib -lTinyGL -L/opt/local/lib -lSDL2


all:	gears

gears:	gears.o
	$(CC)  -o gears.code.bin gears.o ../../src/*.o $(LDFLAGS)
	$(HOME)/sdl2macos9/bin2app.sh gears

clean:
	rm -rf game hello gears model texture *.o *.APPL *.bin *.gdb *.dsk *.pef
