include config.mk.r68

all:
#	( for f in $(DIRS); do ( cd $$f ; make -f Makefile.r68 all ) || exit 1 ; done )
	make  -C source -f Makefile.r68
	make  -C agl-mini -f Makefile.r68
	make  -C GLUT_apple -f Makefile.r68
	cp */*.a .
	make  -C examples -f Makefile.r68
	$(AR) rcv libOpenGLLibrary.a source/*.o agl-mini/*.o
	$(RANLIB) libOpenGLLibrary.a
	$(AR) rcv libOpenGLUtility.a src-glu/*.o
	$(RANLIB) libOpenGLUtility.a

install:
	make -f Makefile.r68 all
	cp *.a $(HOME)/Retro68-build/toolchain/m68k-apple-macos/lib/.
	
clean:
	rm -f *~ lib/libTinyGL.a include/GL/*~ TAGS
#	( for f in $(DIRS); do ( cd $$f ; make -f Makefile.r68 clean ; ) done )
	make  -C source -f Makefile.r68 clean
	make  -C examples -f Makefile.r68 clean
	make  -C agl-mini -f Makefile.r68 clean
	make  -C GLUT_apple -f Makefile.r68 clean
	rm -rf *.a

install:
#	( for f in $(DIRS); do ( cd $$f ; make -f Makefile.r68 install ; ) done )


tar:
#	( cd .. ; tar zcvf /tmp/TinyGL-0.4.1.tar.gz TinyGL --exclude .svn --exclude TAGS )
