LIBNAME=agl

CC=m68k-apple-macos-gcc
CXX=m68k-apple-macos-g++
AR=m68k-apple-macos-ar
RANLIB=m68k-apple-macos-ranlib
#CC=powerpc-apple-macos-gcc
#CXX=powerpc-apple-macos-g++
#AR=powerpc-apple-macos-ar
#RANLIB=powerpc-apple-macos-ranlib

CFLAGS= -I../Headers -I../GL -DUSE_MGL_NAMESPACE=1

OBJS=$(subst .c,.o,$(wildcard *.c))

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<


all: $(OBJS)
	make -f Makefile.r68 -C aglDD

lib: $(OBJS)
	$(AR) rcv lib$(LIBNAME).a *.o */*.o
	$(RANLIB) lib$(LIBNAME).a
	cp *.a ../lib

clean:
	make -f Makefile.r68 -C aglDD clean
	rm -f *.o */*.o
