
#CC=m68k-apple-macos-gcc
#CXX=m68k-apple-macos-g++
CC=powerpc-apple-macos-gcc
CXX=powerpc-apple-macos-g++

CFLAGS= -I../../Headers
LDFLAGS=-lglut -lMesaOpenGLUtility -lMesaOpenGLLibrary -lm

OBJS=$(subst .c,.o,$(wildcard *.c)) $(subst .cpp,.o,$(wildcard *.cpp))

.cpp.o:
	$(CXX) $(CFLAGS) -c -o $@ $<

.c.o:
	$(CXX) $(CFLAGS) -c -o $@ $<

all: $(OBJS)
#	$(CXX) -o underwater.code.bin $(OBJS) $(LDFLAGS)
#	../bin2app.sh underwater
	$(CC) -o underwater $(OBJS) $(LDFLAGS)
	../xcoff2app.sh underwater

clean:
	rm -f *.o *.bin *.pef *.APPL *.dsk *.gdb underwater
