
CC = m68k-apple-macos-gcc
CXX = m68k-apple-macos-gcc


CFLAGS=-I../../include -I.. -I../../stb -I$(HOME)/Retro68-build/toolchain/m68k-apple-macos/include/SDL2 -DSTBI_NO_THREAD_LOCALS
LDFLAGS= $(HOME)/sdl2macos9/SDL-main/src/main/macosclassic/SDL_main.o  -lSDL2  $(HOME)/sdl2macos9/macos8addons/libmacos8addons.a -lInputSprocketLib -lm  
#CFLAGS=-I../../include -I.. -I/opt/local/include/SDL2 -I../../../stb
#LDFLAGS=-L../../lib -lTinyGL -L/opt/local/lib -lSDL2


all:	gears game hello model texture

gears:	gears.o
	$(CC)  -o gears.code.bin gears.o ../../src/*.o $(LDFLAGS)
	$(HOME)/sdl2macos9/bin2app.sh gears

game:	game.o
	$(CC)  -o game.code.bin game.o ../../src/*.o $(LDFLAGS)
	$(HOME)/sdl2macos9/bin2app.sh game

hello:	hello.o
	$(CC)  -o hello.code.bin hello.o ../../src/*.o $(LDFLAGS)
	$(HOME)/sdl2macos9/bin2app.sh hello

model:	model.o
	$(CC)  -o model.code.bin model.o ../../src/*.o $(LDFLAGS)
	$(HOME)/sdl2macos9/bin2app.sh model

texture:	texture.o
	$(CC)  -o texture.code.bin texture.o ../../src/*.o $(LDFLAGS)
	$(HOME)/sdl2macos9/bin2app.sh texture

clean:
	rm -rf game hello gears model texture *.o *.APPL *.bin *.gdb *.dsk *.pef

