
CC=m68k-apple-macos-gcc
CXX=m68k-apple-macos-g++
#CC=powerpc-apple-macos-gcc
#CXX=powerpc-apple-macos-g++

CFLAGS= -I../../include
LDFLAGS=-L../.. -lglut -lOpenGLUtility -lOpenGLLibrary -lm

OBJS=$(subst .c,.o,$(wildcard *.c)) $(subst .cpp,.o,$(wildcard *.cpp))

.cpp.o:
	$(CXX) $(CFLAGS) -c -o $@ $<

.c.o:
	$(CXX) $(CFLAGS) -c -o $@ $<

all: $(OBJS)
	$(CXX) -o opengl_logo.code.bin $(OBJS) $(LDFLAGS)
	../bin2app.sh opengl_logo
#	$(CC) -o opengl_logo $(OBJS) $(LDFLAGS)
#	$(HOME)/sdl2macos9/xcoff2app.sh opengl_logo

clean:
	rm -f *.o *.bin *.pef *.APPL *.dsk *.gdb opengl_logo
