LIBNAME=gl

CC=m68k-apple-macos-gcc
CXX=m68k-apple-macos-g++
AR=m68k-apple-macos-ar
RANLIB=m68k-apple-macos-ranlib
#CC=powerpc-apple-macos-gcc
#CXX=powerpc-apple-macos-g++
#AR=powerpc-apple-macos-ar
#RANLIB=powerpc-apple-macos-ranlib

CFLAGS= -I../Headers -I../GL/Sources -DUSE_MGL_NAMESPACE=1

OBJS=$(subst .c,.o,$(wildcard *.c))

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<


all: $(OBJS)

lib: $(OBJS)
	$(AR) rcv lib$(LIBNAME).a *.o
	$(RANLIB) lib$(LIBNAME).a
	cp *.a ../lib

clean:
	rm -f *.o */*.o *.a
